version: '2'
services:
  auth_db:
    image: postgres:14.8-alpine
    restart: always
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 3307:3306
      - 5432:5432
    expose:
      - 5432
    volumes:
      - auth_db_data:/var/lib/postgresql/auth/data
    networks:
      - kafka-app
  auth:
    build:
      context: ./auth
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - auth_db
      - kafka
    links:
      - auth_db
      - kafka
    env_file:
      - "auth/env.dev"
    networks:
      - kafka-app

  tasks_db:
    image: postgres:14.8-alpine
    restart: always
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 3308:3306
      - 5433:5432
    expose:
      - 5432
    volumes:
      - tasks_db_data:/var/lib/postgresql/tasks/data
    networks:
      - kafka-app
  tasks:
    build:
      context: ./tasks
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    depends_on:
      - tasks_db
      - kafka
    links:
      - tasks_db
      - kafka
    env_file:
      - "tasks/env.dev"
    networks:
      - kafka-app
  tasks-karafka-server:
    build:
      context: ./tasks
    command: bundle exec karafka server
    volumes:
      - ".:/app"
    depends_on:
      - tasks_db
      - kafka
    links:
      - tasks_db
      - kafka
    env_file:
      - "tasks/env.dev"
    networks:
      - kafka-app

  zookeeper:
    image: wurstmeister/zookeeper
    restart: on-failure
    ports:
      - '2181:2181'
    networks:
      - kafka-app
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka/data
    restart: on-failure
    networks:
      - kafka-app

volumes:
  auth_db_data:
  tasks_db_data:
  kafka_data:

networks:
  kafka-app:
    driver: bridge
